name: MLflow CI Training

on:
  push:
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: msml
          environment-file: MLProject/conda.yaml
          auto-activate-base: false

      - name: Install MLflow
        run: |
          conda install -c conda-forge mlflow

      - name: Run MLflow Project Training
        run: |
          cd MLProject
          mlflow run . --entry-point main

      - name: Find latest run ID
        id: get_run
        run: |
          RUN_ID=$(ls -t mlruns/0 | head -n 1)
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

      - name: Upload model artifact
        uses: actions/upload-artifact@v3
        with:
          name: mlflow-model
          path: mlruns/0/${{ steps.get_run.outputs.run_id }}/artifacts/model

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image from MLflow Model
        run: |
          mlflow models build-docker -m mlruns/0/${{ steps.get_run.outputs.run_id }}/artifacts/model -n fiqih-mlflow-model

      - name: Push Docker Image
        run: |
          docker tag fiqih-mlflow-model ${{ secrets.DOCKER_USERNAME }}/fiqih-mlflow-model:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/fiqih-mlflow-model:latest
