name: Preprocessing Pipeline

on:
  push:
    paths:
      - 'preprocessing/**'
      - '.github/workflows/preprocess.yml'
  workflow_dispatch:

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Membangun_model/requirements.txt

      - name: Run preprocessing
        run: |
          python Membangun_model/automate_Fiqih.py

      - name: Upload processed dataset
        uses: actions/upload-artifact@v3
        with:
          name: processed-dataset
          path: Membangun_model/nasa_preprocessing/clean